<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Title>OneOf - Discriminated Unions for C#</Title>
    <Description>Discriminated unions for C# with exhaustive matching through OneOf&lt;T0, ... Tn&gt;.</Description>
    <PackageTags>discriminated-unions;return-type;match;switch</PackageTags>
    <PackageId>Vaerktojer.OneOf</PackageId>
    <IsPackable>true</IsPackable>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
    <None Include="..\README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
