using System;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace OneOf.SourceGenerator.AnalyzerTests
{
    public class AnalyzerTests
    {
        [Fact]
        public void GenerateOneOfAttribute()
        {
            const string expectedCode = @"// <auto-generated />
using System;

#pragma warning disable 1591

namespace OneOf
{
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class GenerateOneOfAttribute : Attribute
    {
    }
}
";
            AssertCorrectSourceCodeIsGeneratedWithNoDiagnostics(string.Empty, expectedCode, "GenerateOneOfAttribute.g.cs", 2);
        }

        [Fact]
        public void GeneratesPublicClass()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    [GenerateOneOf]
    public partial class StringOrNumber : OneOfBase<string, int, uint> { }
}
";

            const string expectedCode = @"// <auto-generated />
#pragma warning disable 1591

namespace Foo
{
    partial class StringOrNumber
    {
        public StringOrNumber(global::OneOf.OneOf<string, int, uint> _) : base(_) { }

        public static implicit operator StringOrNumber(string _) => new StringOrNumber(_);
        public static explicit operator string(StringOrNumber _) => _.AsT0;

        public static implicit operator StringOrNumber(int _) => new StringOrNumber(_);
        public static explicit operator int(StringOrNumber _) => _.AsT1;

        public static implicit operator StringOrNumber(uint _) => new StringOrNumber(_);
        public static explicit operator uint(StringOrNumber _) => _.AsT2;
    }
}";

            AssertCorrectSourceCodeIsGeneratedWithNoDiagnostics(input, expectedCode, "Foo.StringOrNumber.g.cs");
        }

        [Fact]
        public void GeneratesInternalClass()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    [GenerateOneOf]
    internal partial class StringOrNumber : OneOfBase<string, int, uint> { }
}
";

            const string expectedCode = @"// <auto-generated />
#pragma warning disable 1591

namespace Foo
{
    partial class StringOrNumber
    {
        public StringOrNumber(global::OneOf.OneOf<string, int, uint> _) : base(_) { }

        public static implicit operator StringOrNumber(string _) => new StringOrNumber(_);
        public static explicit operator string(StringOrNumber _) => _.AsT0;

        public static implicit operator StringOrNumber(int _) => new StringOrNumber(_);
        public static explicit operator int(StringOrNumber _) => _.AsT1;

        public static implicit operator StringOrNumber(uint _) => new StringOrNumber(_);
        public static explicit operator uint(StringOrNumber _) => _.AsT2;
    }
}";

            AssertCorrectSourceCodeIsGeneratedWithNoDiagnostics(input, expectedCode, "Foo.StringOrNumber.g.cs");
        }

        [Fact]
        public void GeneratesInternalClassWithoutExplicitVisibility()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    [GenerateOneOf]
    partial class StringOrNumber : OneOfBase<string, int, uint> { }
}
";

            const string expectedCode = @"// <auto-generated />
#pragma warning disable 1591

namespace Foo
{
    partial class StringOrNumber
    {
        public StringOrNumber(global::OneOf.OneOf<string, int, uint> _) : base(_) { }

        public static implicit operator StringOrNumber(string _) => new StringOrNumber(_);
        public static explicit operator string(StringOrNumber _) => _.AsT0;

        public static implicit operator StringOrNumber(int _) => new StringOrNumber(_);
        public static explicit operator int(StringOrNumber _) => _.AsT1;

        public static implicit operator StringOrNumber(uint _) => new StringOrNumber(_);
        public static explicit operator uint(StringOrNumber _) => _.AsT2;
    }
}";

            AssertCorrectSourceCodeIsGeneratedWithNoDiagnostics(input, expectedCode, "Foo.StringOrNumber.g.cs");
        }
        
        [Fact]
        public void Class_Must_Be_Top_Level()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    public static class A
    {
        [GenerateOneOf]
        public partial class StringOrNumber : OneOfBase<string, int> { }
    }
}
";

            AssertDiagnosticErrorIsReturned(input, GeneratorDiagnosticDescriptors.TopLevelError.Id);
        }

        [Fact]
        public void Cannot_Use_Generator_With_Object_type()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    [GenerateOneOf]
    public partial class ObjectOrNumber : OneOfBase<object, int> { }
}
";
            AssertDiagnosticErrorIsReturned(input, GeneratorDiagnosticDescriptors.ObjectIsOneOfType.Id);
        }

        [Fact]
        public void Class_Must_Be_Derived_From_OneOfBase()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    [GenerateOneOf]
    public partial class ObjectOrNumber : MyClass { }

    public class MyClass
    {
    }
}
";
            AssertDiagnosticErrorIsReturned(input, GeneratorDiagnosticDescriptors.WrongBaseType.Id);
        }

        [Fact]
        public void User_Defined_Conversions_To_Or_From_An_Interface_Are_Not_Allowed()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    [GenerateOneOf]
    public partial class ObjectOrNumber : OneOfBase<IFoo, int> { }

    public interface IFoo
    {
    }
}
";
            AssertDiagnosticErrorIsReturned(input, GeneratorDiagnosticDescriptors.UserDefinedConversionsToOrFromAnInterfaceAreNotAllowed.Id);
        }
        
        [Fact]
        public void GeneratesClassWithConflictingNamespaces()
        {
            const string input = $@"
using OneOf;
using Bar;
using Foo.Bar;

namespace Foo.Bar 
{{
    public class Class1
    {{
    }}
}}

namespace Bar 
{{
    public class Class2
    {{
    }}
}}

namespace Foo
{{
    [GenerateOneOf]
    partial class FooBar : OneOfBase<Class1, Class2> {{ }}
}}
";

            const string expectedCode = @"// <auto-generated />
#pragma warning disable 1591

namespace Foo
{
    partial class FooBar
    {
        public FooBar(global::OneOf.OneOf<global::Foo.Bar.Class1, global::Bar.Class2> _) : base(_) { }

        public static implicit operator FooBar(global::Foo.Bar.Class1 _) => new FooBar(_);
        public static explicit operator global::Foo.Bar.Class1(FooBar _) => _.AsT0;

        public static implicit operator FooBar(global::Bar.Class2 _) => new FooBar(_);
        public static explicit operator global::Bar.Class2(FooBar _) => _.AsT1;
    }
}";

            AssertCorrectSourceCodeIsGeneratedWithNoDiagnostics(input, expectedCode, "Foo.FooBar.g.cs");
        }

        [Fact]
        public void GeneratesClassInGlobalNamespace()
        {
            const string input = @"
using OneOf;

[GenerateOneOf]
public partial class StringOrNumber : OneOfBase<string, int> { }
";

            const string expectedCode = @"// <auto-generated />
#pragma warning disable 1591

partial class StringOrNumber
{
    public StringOrNumber(global::OneOf.OneOf<string, int> _) : base(_) { }

    public static implicit operator StringOrNumber(string _) => new StringOrNumber(_);
    public static explicit operator string(StringOrNumber _) => _.AsT0;

    public static implicit operator StringOrNumber(int _) => new StringOrNumber(_);
    public static explicit operator int(StringOrNumber _) => _.AsT1;
}";

            AssertCorrectSourceCodeIsGeneratedWithNoDiagnostics(input, expectedCode, "StringOrNumber.g.cs");
        }

        [Fact]
        public void GeneratedClassIsCompatibleWithCSharp73()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    [GenerateOneOf]
    public partial class StringOrNumber : OneOfBase<string, int> { }
}
";

            var inputCompilation = CreateCompilation(input);
            GeneratorDriver driver = CSharpGeneratorDriver.Create(new OneOfGenerator());

            driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);

            var generatedSource = outputCompilation.SyntaxTrees.Single(tree => tree.FilePath.Contains("Foo.StringOrNumber.g.cs"));
            var csharp73Source = CSharpSyntaxTree.ParseText(
                generatedSource.GetText(),
                new CSharpParseOptions(LanguageVersion.CSharp7_3));

            Assert.Empty(csharp73Source.GetDiagnostics());
        }

        [Fact]
        public void GenericAritiesHaveDistinctHintNames()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    [GenerateOneOf]
    public partial class Result<T> : OneOfBase<string, int> { }

    [GenerateOneOf]
    public partial class Result<T, TError> : OneOfBase<string, int> { }
}
";

            var inputCompilation = CreateCompilation(input);
            GeneratorDriver driver = CSharpGeneratorDriver.Create(new OneOfGenerator());

            driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

            Assert.True(diagnostics.IsEmpty);
            Assert.Empty(outputCompilation.GetDiagnostics());
            Assert.Contains(outputCompilation.SyntaxTrees, tree => tree.FilePath.Contains("Foo.Result`1.g.cs"));
            Assert.Contains(outputCompilation.SyntaxTrees, tree => tree.FilePath.Contains("Foo.Result`2.g.cs"));
        }

        [Fact]
        public void NamespaceAndTypeBoundariesHaveDistinctHintNames()
        {
            const string input = @"
using OneOf;

namespace A
{
    [GenerateOneOf]
    public partial class B_C : OneOfBase<string, int> { }
}

namespace A_B
{
    [GenerateOneOf]
    public partial class C : OneOfBase<string, int> { }
}
";

            var inputCompilation = CreateCompilation(input);
            GeneratorDriver driver = CSharpGeneratorDriver.Create(new OneOfGenerator());

            driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

            Assert.True(diagnostics.IsEmpty);
            Assert.Empty(outputCompilation.GetDiagnostics());
            Assert.Contains(outputCompilation.SyntaxTrees, tree => tree.FilePath.Contains("A.B_C.g.cs"));
            Assert.Contains(outputCompilation.SyntaxTrees, tree => tree.FilePath.Contains("A_B.C.g.cs"));
        }

        [Fact]
        public void UserDefinedTypeNamedObjectIsAllowed()
        {
            const string input = @"
using OneOf;

namespace Foo
{
    public class Object { }

    [GenerateOneOf]
    public partial class ObjectOrNumber : OneOfBase<Object, int> { }
}
";

            var inputCompilation = CreateCompilation(input);
            GeneratorDriver driver = CSharpGeneratorDriver.Create(new OneOfGenerator());

            driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

            Assert.True(diagnostics.IsEmpty);
            Assert.Empty(outputCompilation.GetDiagnostics());
        }

        [Fact]
        public void EscapesKeywordClassNamesAndGlobalOneOfNamespace()
        {
            const string input = @"
namespace Foo
{
    public class OneOf { }

    [global::OneOf.GenerateOneOf]
    public partial class @class : global::OneOf.OneOfBase<string, int> { }
}
";

            var inputCompilation = CreateCompilation(input);
            GeneratorDriver driver = CSharpGeneratorDriver.Create(new OneOfGenerator());

            driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

            Assert.True(diagnostics.IsEmpty);
            Assert.Empty(outputCompilation.GetDiagnostics());
        }

        private static void AssertCorrectSourceCodeIsGeneratedWithNoDiagnostics(string inputSource, string expectedCode, string generatedFileName, int expectedCompilationFileCount = 3)
        {
            var parsedAttribute = CSharpSyntaxTree.ParseText(expectedCode);

            var inputCompilation = CreateCompilation(inputSource);

            GeneratorDriver driver = CSharpGeneratorDriver.Create(new OneOfGenerator());

            driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

            Assert.True(diagnostics.IsEmpty);

            Assert.Equal(expectedCompilationFileCount, outputCompilation.SyntaxTrees.Count());

            Assert.Empty(outputCompilation.GetDiagnostics());

            var compiledAttribute = outputCompilation.SyntaxTrees.Single(e => e.FilePath.Contains(generatedFileName));

            Assert.True(parsedAttribute.IsEquivalentTo(compiledAttribute));

            Assert.True(outputCompilation.GetDiagnostics().IsEmpty);
        }

        private static void AssertDiagnosticErrorIsReturned(string inputSource, string diagnosticId)
        {
            var inputCompilation = CreateCompilation(inputSource);

            GeneratorDriver driver = CSharpGeneratorDriver.Create(new OneOfGenerator());

            driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out _, out var diagnostics);

            Assert.Contains(diagnostics, d => d.Id == diagnosticId && d.Severity == DiagnosticSeverity.Error);
        }

        private static Compilation CreateCompilation(string source)
        {
            var trustedPlatformAssemblies = (string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!;
            var references = trustedPlatformAssemblies
                .Split(Path.PathSeparator)
                .Select(path => MetadataReference.CreateFromFile(path))
                .Append(MetadataReference.CreateFromFile(typeof(OneOfBase<>).Assembly.Location));

            return CSharpCompilation.Create("compilation", new[] { CSharpSyntaxTree.ParseText(source) }, references, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        }
    }
}
