using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace OneOf.SourceGenerator
{
    [Generator]
    public class OneOfGenerator : IIncrementalGenerator
    {
        private const string AttributeName = "GenerateOneOfAttribute";
        private const string AttributeNamespace = "OneOf";

        private readonly string _attributeText = $@"// <auto-generated />
using System;

#pragma warning disable 1591

namespace {AttributeNamespace}
{{
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class {AttributeName} : Attribute
    {{
    }}
}}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource($"{AttributeName}.g.cs", _attributeText));
            
            var oneOfClasses = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    fullyQualifiedMetadataName: $"{AttributeNamespace}.{AttributeName}",
                    predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null)
                .Select(static (symbol, _) => symbol!);

            context.RegisterSourceOutput(
                oneOfClasses.Combine(context.CompilationProvider),
                static (ctx, input) => Execute(ctx, input.Left, input.Right));
        }

        private static bool IsSyntaxTargetForGeneration(SyntaxNode node) =>
            node is ClassDeclarationSyntax classDeclarationSyntax
            && classDeclarationSyntax.Modifiers.Any(SyntaxKind.PartialKeyword);

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorAttributeSyntaxContext context) =>
            context.TargetSymbol as INamedTypeSymbol;

        private static string GenerateClassSource(INamedTypeSymbol classSymbol,
            ImmutableArray<ITypeParameterSymbol> typeParameters, ImmutableArray<ITypeSymbol> typeArguments)
        {
            var paramArgPairs =
                typeParameters.Zip(typeArguments, (param, arg) => (param, arg));

            var oneOfGenericPart = GetGenericPart(typeArguments);

            var className = EscapeIdentifier(classSymbol.Name);
            var classNameWithGenericTypes = $"{className}{GetOpenGenericPart(classSymbol)}";
            var hasNamespace = !classSymbol.ContainingNamespace.IsGlobalNamespace;
            var classIndent = hasNamespace ? "    " : string.Empty;
            var memberIndent = hasNamespace ? "        " : "    ";

            var source = new StringBuilder($@"// <auto-generated />
#pragma warning disable 1591
");

            if (hasNamespace)
            {
                source.Append($@"
namespace {classSymbol.ContainingNamespace.ToDisplayString()}
{{");
            }

            source.Append($@"
{classIndent}partial class {classNameWithGenericTypes}");

            source.Append($@"
{classIndent}{{
{memberIndent}public {className}(global::OneOf.OneOf<{oneOfGenericPart}> _) : base(_) {{ }}
");

            foreach (var (param, arg) in paramArgPairs)
            {
                source.Append($@"
{memberIndent}public static implicit operator {classNameWithGenericTypes}({arg.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} _) => new {classNameWithGenericTypes}(_);
{memberIndent}public static explicit operator {arg.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}({classNameWithGenericTypes} _) => _.As{param.Name};
");
            }

            source.Append($@"{classIndent}}}");

            if (hasNamespace)
            {
                source.Append(@"
}");
            }

            return source.ToString();
        }

        private static void Execute(SourceProductionContext context, INamedTypeSymbol namedTypeSymbol, Compilation compilation)
        {
            var classSource = ProcessClass(namedTypeSymbol, compilation, context);

            if (classSource is null)
            {
                return;
            }

            var namespacePrefix = namedTypeSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : $"{namedTypeSymbol.ContainingNamespace.ToDisplayString()}.";
            context.AddSource($"{namespacePrefix}{namedTypeSymbol.MetadataName}.g.cs", classSource);
        }

        private static string? ProcessClass(INamedTypeSymbol classSymbol, Compilation compilation, SourceProductionContext context)
        {
            var attributeLocation = classSymbol.Locations.FirstOrDefault() ?? Location.None;

            if (!classSymbol.ContainingSymbol.Equals(classSymbol.ContainingNamespace, SymbolEqualityComparer.Default))
            {
                CreateDiagnosticError(GeneratorDiagnosticDescriptors.TopLevelError);
                return null;
            }

            var baseType = classSymbol.BaseType;
            var expectedBaseType = baseType is null
                ? null
                : compilation.GetTypeByMetadataName($"OneOf.OneOfBase`{baseType.Arity}");

            if (baseType is null
                || expectedBaseType is null
                || !SymbolEqualityComparer.Default.Equals(baseType.OriginalDefinition, expectedBaseType))
            {
                CreateDiagnosticError(GeneratorDiagnosticDescriptors.WrongBaseType);
                return null;
            }

            var typeArguments = baseType.TypeArguments;

            foreach (var typeSymbol in typeArguments)
            {
                if (typeSymbol.SpecialType == SpecialType.System_Object)
                {
                    CreateDiagnosticError(GeneratorDiagnosticDescriptors.ObjectIsOneOfType);
                    return null;
                }

                if (typeSymbol.TypeKind == TypeKind.Interface)
                {
                    CreateDiagnosticError(GeneratorDiagnosticDescriptors.UserDefinedConversionsToOrFromAnInterfaceAreNotAllowed);
                    return null;
                }
            }

            return GenerateClassSource(classSymbol, baseType.TypeParameters, typeArguments);

            void CreateDiagnosticError(DiagnosticDescriptor descriptor)
            {
                context.ReportDiagnostic(Diagnostic.Create(descriptor, attributeLocation, classSymbol.Name,
                    DiagnosticSeverity.Error));
            }
        }

        private static string GetGenericPart(ImmutableArray<ITypeSymbol> typeArguments) =>
            string.Join(", ", typeArguments.Select(x => x.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

        private static string? GetOpenGenericPart(INamedTypeSymbol classSymbol)
        {
            if (!classSymbol.TypeArguments.Any())
            {
                return null;
            }

            return $"<{GetGenericPart(classSymbol.TypeArguments)}>";
        }

        private static string EscapeIdentifier(string identifier) =>
            SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : $"@{identifier}";
    }
}
