<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>akifisitan</Authors>
    <Title>OneOf.SourceGenerator - OneOfBase Source Generator</Title>
    <Description>Generates constructors and conversions for OneOfBase hierarchies.</Description>
    <PackageTags>discriminated-unions;return-type;match;switch;source-generator</PackageTags>
    <PackageId>Vaerktojer.OneOf.SourceGenerator</PackageId>
    <IsPackable>true</IsPackable>
    <RootNamespace>OneOf</RootNamespace>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="..\README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1">
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
  </ItemGroup>

</Project>
