<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Title>OneOf.Extended - Discriminated Unions for C#</Title>
    <Description>Extends OneOf with unions containing 10 to 32 alternatives.</Description>
    <PackageTags>discriminated-unions;return-type;match;switch</PackageTags>
    <PackageId>Vaerktojer.OneOf.Extended</PackageId>
    <IsPackable>true</IsPackable>
    <RootNamespace>OneOf</RootNamespace>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
    <None Include="..\README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OneOf\OneOf.csproj" />
  </ItemGroup>

</Project>
